apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1  # Number of pods to run
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 241533159425.dkr.ecr.ap-south-1.amazonaws.com/backend:1  # Replace with your backend image version
          ports:
            - containerPort: 5000  # Port inside the container where Flask app runs

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend  # Matches the deployment's label
  ports:
    - protocol: TCP
      port: 8001  # External port you want to expose (choose a unique port)
      targetPort: 5000  # Internal container port
      nodePort: 30001  # The port on the node (choose an open port)
  type: NodePort  # Type to expose via NodePort (not LoadBalancer)
